### ISSUE TITLE
Template not found: map.jinja

### ISSUE THREAD

**Issue by TTimo** [gspe/dropbox-formula#1]
Hello, getting the following when trying to use this formula - any ideas?

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:dropbox' failed: Jinja error: map.jinja
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/dist-packages/salt/utils/jinja.py", line 144, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: map.jinja

; line 1

---
{% from 'map.jinja' import dist with context %}    <======================

{% if grains['os_family'] == 'Debian' %}
dropbox-pkg:
  pkgrepo.managed:
    - humanname: Dropbox
[...]

---
```

**Comment by Ciemaar** [comment]
I amended the first line to:

{% from '**dropbox**/map.jinja' import dist with context %}

and that took care of finding the map file, not sure if this is a proper fix or not.
